#! /bin/sh
#
# This script is used to connect to a bluetooth device
#

bluetoothctl << EOF
connect 14:3F:A6:29:0E:A2
EOF

# Corsair headphones
#connect FC:58:FA:0E:09:86

#ITB tower
#connect A4:DE:E5:02:80:33

# Sony Headphones WH-1000XM4
#connect 14:3F:A6:29:0E:A2



